"""
MatIntel – Main Controller
===========================
Entry point for the entire project. Run with:

    python main.py

What this does:
  1. Trains the model (runs train_model.py) if any required artifact is missing.
  2. Loads model_service so the trained model is in memory.
  3. Patches app.py's /predict route to call the real model instead of the placeholder.
  4. Starts the Flask server.

Expected project layout:
    main.py
    app.py
    model_service.py
    train_model.py
    templates/
        matintel.html          ← Flask requires templates in a subfolder
    synthesis/
        master_training_dataset.csv
    matintel_model.h5          ← generated by train_model.py
    scaler.pkl                 ← generated by train_model.py
    y_scaler.pkl               ← generated by train_model.py
    properties.pkl             ← generated by train_model.py
    feature_columns.pkl        ← generated by train_model.py
    input_medians.pkl          ← generated by train_model.py
"""

import os
import runpy

# ---------------------------------------------------------------------------
# 1. TRAIN if any artifact is missing
# ---------------------------------------------------------------------------
ARTIFACTS = [
    "matintel_model.h5",
    "scaler.pkl",
    "y_scaler.pkl",
    "properties.pkl",
    "feature_columns.pkl",
    "input_medians.pkl",
]

if any(not os.path.exists(a) for a in ARTIFACTS):
    print("=" * 60)
    print("One or more model artifacts not found. Running training...")
    print("=" * 60)
    runpy.run_path("train_model.py", run_name="__main__")
    print("=" * 60)
    print("Training complete.")
    print("=" * 60)
else:
    print("Model artifacts found. Skipping training.")

# ---------------------------------------------------------------------------
# 2. LOAD model_service (imports TF model + scalers into memory once)
# ---------------------------------------------------------------------------
print("Loading model service...")
import model_service  # noqa: E402  (intentionally after artifact check)

# ---------------------------------------------------------------------------
# 3. IMPORT app and wire the real predict function into the /predict route
# ---------------------------------------------------------------------------
from flask import Flask, render_template, request  # noqa: E402

# Re-create the Flask app here so we control the template folder.
# matintel.html must live in a `templates/` subfolder next to main.py.
templates_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "templates")
if not os.path.isdir(templates_dir):
    os.makedirs(templates_dir)
    print(f"Created templates/ directory at {templates_dir}")

html_src = os.path.join(os.path.dirname(os.path.abspath(__file__)), "matintel.html")
html_dst = os.path.join(templates_dir, "matintel.html")
if os.path.exists(html_src) and not os.path.exists(html_dst):
    import shutil
    shutil.copy(html_src, html_dst)
    print("Copied matintel.html → templates/matintel.html")

app = Flask(__name__, template_folder=templates_dir)

# ---------------------------------------------------------------------------
# Track / output definitions (mirrors app.py and matintel.html)
# ---------------------------------------------------------------------------
CHEMISTRY_PROPS = {"C_Wt_%", "Mn_Wt_%", "P_Wt_%", "S_Wt_%",
                   "Si_Wt_%", "Ni_Wt_%", "Cr_Wt_%", "Mo_Wt_%", "Ti_Wt_%"}
PHYSICS_PROPS   = {"Density_(g/cm3)", "Energy_Above_Hull_(eV)",
                   "Bulk_Modulus_(GPa)", "Shear_Modulus_(GPa)"}
CHEMISTRY_OUTPUTS = {"Ultimate_Tensile_Strength_(MPa)", "Yield_Strength_(MPa)",
                     "Elongation_(%)", "Hardness_(HB)"}
PHYSICS_OUTPUTS   = {"Density_(g/cm3)", "Energy_Above_Hull_(eV)",
                     "Bulk_Modulus_(GPa)", "Shear_Modulus_(GPa)"}

# ---------------------------------------------------------------------------
# Confidence helper
# A simple proxy: penalise predictions that required many imputed inputs.
# When the model has no real signal (all inputs missing) confidence is lower.
# ---------------------------------------------------------------------------
def compute_confidence(user_inputs: dict) -> float:
    composition_features = [c for c in model_service.composition_features]
    n_provided = sum(1 for c in composition_features if c in user_inputs)
    n_total = len(composition_features)
    # Scale linearly: 0 inputs → 0.50, all inputs → 0.95
    return round(0.50 + 0.45 * (n_provided / max(n_total, 1)), 2)

# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------
@app.route("/", methods=["GET"])
def index():
    return render_template("matintel.html",
                           predictions=None,
                           similar_materials=None,
                           track=None)


@app.route("/predict", methods=["POST"])
def predict():
    material = request.form.get("material", "").strip()

    # Parse parallel property / value lists from the form
    properties  = request.form.getlist("properties")
    values      = request.form.getlist("values")

    inputs = []
    for p, v in zip(properties, values):
        if p and v:
            try:
                inputs.append({"property": p, "value": float(v)})
            except ValueError:
                continue

    # Detect track
    supplied = {row["property"] for row in inputs}
    if supplied & CHEMISTRY_PROPS:
        track = "chemistry"
    elif supplied & PHYSICS_PROPS:
        track = "physics"
    else:
        track = "chemistry"

    # Requested output properties
    predict_properties = request.form.getlist("predict_properties")
    allowed_outputs = CHEMISTRY_OUTPUTS if track == "chemistry" else PHYSICS_OUTPUTS

    # Build the input dict expected by model_service.predict()
    user_inputs = {row["property"]: row["value"] for row in inputs}

    # Run the real model
    all_predictions = model_service.predict(user_inputs)

    # Filter to only the properties the user selected AND that belong to this track
    requested = set(predict_properties) & allowed_outputs
    confidence = compute_confidence(user_inputs)

    predictions = [
        {
            "property":   p["property"],
            "value":      p["value"],
            "confidence": confidence,
        }
        for p in all_predictions
        if p["property"] in requested
    ]

    # Similar materials placeholder (replace with a real nearest-neighbour lookup)
    similar_materials = []

    return render_template(
        "matintel.html",
        predictions=predictions,
        similar_materials=similar_materials,
        material=material,
        inputs=inputs,
        track=track,
    )


# ---------------------------------------------------------------------------
# 4. START SERVER
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    print("Starting MatIntel server at http://127.0.0.1:5000")
    app.run(debug=False, host="0.0.0.0", port=5000)
